# Generated by Django 5.1.6 on 2025-02-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('childcare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='adddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='adddress',
            new_name='address',
        ),
    ]
