# Generated by Django 5.1.6 on 2025-02-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childcare', '0002_rename_adddress_parent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
