# Generated by Django 5.1.6 on 2025-03-25 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childcare', '0005_booking_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='childcare.booking')),
                ('children', models.ManyToManyField(related_name='reports', to='childcare.child')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='childcare.staff')),
            ],
        ),
    ]
